# Generated by Django 5.2.16 on 2026-07-09 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatingChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["venue", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="venues.seatingchart",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["chart", "ordering", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_label", models.CharField(max_length=10)),
                ("number", models.CharField(max_length=10)),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("is_accessible", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="venues.section",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "row_label", "number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("timezone", models.CharField(default="UTC", max_length=63)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="seatingchart",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seating_charts",
                to="venues.venue",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["organization"], name="venues_sect_organiz_4a2c89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["chart"], name="venues_sect_chart_i_a35e1c_idx"),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("chart", "name"), name="unique_section_name_per_chart"
            ),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["organization"], name="venues_seat_organiz_625234_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["section"], name="venues_seat_section_bcb762_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("section", "row_label", "number"),
                name="unique_seat_per_section",
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["organization"], name="venues_venu_organiz_5a813f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seatingchart",
            index=models.Index(
                fields=["organization"], name="venues_seat_organiz_dfff05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seatingchart",
            index=models.Index(fields=["venue"], name="venues_seat_venue_i_a90758_idx"),
        ),
        migrations.AddConstraint(
            model_name="seatingchart",
            constraint=models.UniqueConstraint(
                fields=("venue", "name"), name="unique_chart_name_per_venue"
            ),
        ),
    ]
