# Generated by Django 5.2.16 on 2026-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="arc_radius",
            field=models.FloatField(
                blank=True,
                help_text="Radius for a fanned/curved section. Not yet used for seat placement -- Phase A always generates a straight (optionally rotated) grid; reserved for Phase B's fanned-section geometry.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="numbering_scheme",
            field=models.CharField(
                choices=[
                    ("sequential", "Sequential (1, 2, 3…)"),
                    ("odd_desc_left", "Odd, descending toward the aisle (…5, 3, 1)"),
                    (
                        "even_asc_right",
                        "Even, ascending away from the aisle (2, 4, 6…)",
                    ),
                    ("hundreds", "Hundreds by row (101, 102… / 201, 202…)"),
                ],
                default="sequential",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="origin_x",
            field=models.FloatField(
                default=0.0, help_text="X of this section's front-left corner."
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="origin_y",
            field=models.FloatField(
                default=0.0, help_text="Y of this section's front-left corner."
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="rotation",
            field=models.FloatField(
                default=0.0,
                help_text="Degrees clockwise the section's seat grid is rotated around its origin. Phase A applies this as a simple whole-grid rotation during generation; per-row raked offsets are Phase B.",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="row_label_scheme",
            field=models.CharField(
                choices=[
                    ("skip_io", "A–Z skipping I/O, then AA, BB…"),
                    ("all_letters", "A–Z including I/O, then AA, BB…"),
                ],
                default="skip_io",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="row_pitch",
            field=models.FloatField(default=1.0, help_text="Spacing between rows."),
        ),
        migrations.AddField(
            model_name="section",
            name="seat_pitch",
            field=models.FloatField(
                default=1.0, help_text="Spacing between adjacent seats in a row."
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="tier",
            field=models.CharField(
                blank=True,
                help_text="Optional grouping label, e.g. Orchestra/Parterre/Balcony. Free text in Phase A; Phase C's visual pricing zones may key off it for defaults/labeling.",
                max_length=100,
            ),
        ),
    ]
