# Generated by Django 5.2.16 on 2026-07-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_section_arc_radius_section_numbering_scheme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="row_x_offset",
            field=models.FloatField(
                default=0.0,
                help_text="Phase B: extra horizontal offset applied per row (before rotation), growing with row_index -- e.g. 0.5 shifts row B 0.5 right of row A, row C 1.0, and so on. This is what turns a raked/diagonal side section into a trapezoid/angled block (combined with ragged per-row seat counts and/or `rotation`) instead of a plain rectangle. 0.0 (default) reproduces Phase A's straight grid exactly.",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="arc_radius",
            field=models.FloatField(
                blank=True,
                help_text="Radius (distance from origin to the front row) for a fanned/curved section, e.g. a center orchestra block. When set, seats in a row are placed along a circular arc of this radius (rows step outward from the origin by row_pitch per row) instead of a straight line -- see venues.generation for the trig. Null/blank (default) means straight (grid or raked, per rotation/row_x_offset).",
                null=True,
            ),
        ),
    ]
