# Generated by Django 5.2.16 on 2026-07-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_section_row_x_offset_alter_section_arc_radius"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="accessible_seats",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[[row_label, number], ...] seat identities flagged accessible via the editor's seat popover. Re-applied on every regenerate, same as removed_seats.",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="alt_row_seat_delta",
            field=models.IntegerField(
                default=0,
                help_text="ALTERNATING offset_mode only: seats added (positive) or dropped (negative) on every other row (row_index 1, 3, 5…), on top of seats_per_row -- e.g. +1 for a brick-stagger row that's one seat longer, -1 for one shorter. Each row is floored at 1 seat. Ignored in REPEATED mode.",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="offset_mode",
            field=models.CharField(
                choices=[
                    ("repeated", "Repeated (constant shift every row)"),
                    ("alternating", "Alternating (stagger every other row)"),
                ],
                default="repeated",
                help_text="How row_x_offset is applied across rows -- see its help text.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="removed_seats",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[[row_label, number], ...] seat identities deleted via the editor's seat popover. Re-applied on every regenerate so a deleted seat (e.g. an aisle gap) stays gone even after live param changes.",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="rows",
            field=models.PositiveIntegerField(
                default=4, help_text="Live editor shape: number of rows to generate."
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="seats_per_row",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Live editor shape: base seats per row. ALTERNATING offset_mode adds alt_row_seat_delta to this on every other row.",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="arc_radius",
            field=models.FloatField(
                blank=True,
                help_text="Curvature radius for a fanned/curved section, e.g. a center orchestra block. When set, seats in a row are placed along a circular arc of this radius instead of a straight line -- the arc curves the rows IN PLACE (the section's front-row-center seat always sits at the section's origin regardless of arc_radius; the radius only controls how tightly the rows bow, not where the section sits) -- see venues.generation._fanned_local, mirrored in static/js/seat_geometry.js. Null/blank (default) means straight (grid or raked, per rotation/row_x_offset).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="row_x_offset",
            field=models.FloatField(
                default=0.0,
                help_text="Offset amount in local x units. Meaning depends on offset_mode: REPEATED applies it every row, growing with row_index (0.5 shifts row B 0.5 right of row A, row C 1.0, and so on -- turns a raked/diagonal side section into a trapezoid). ALTERNATING applies the same constant amount to every OTHER row only (brick/stadium stagger), row_index 1, 3, 5… -- see venues.generation._row_x_offset, mirrored in static/js/seat_geometry.js. 0.0 (default) reproduces a plain grid.",
            ),
        ),
    ]
