# Generated by Django 5.2.16 on 2026-07-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0004_section_accessible_seats_section_alt_row_seat_delta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="pivot_mode",
            field=models.CharField(
                choices=[
                    ("center", "Section center (default)"),
                    ("origin", "Origin (front-left corner)"),
                    ("custom", "Custom (dragged on canvas)"),
                ],
                default="center",
                help_text="Round-2 refinement (docs/EDITOR.md): what point `rotation` pivots around. CENTER (default) is the midpoint of the seats_per_row x rows block (same bounding box the editor's transform-box handles use). ORIGIN is the section's own origin_x/origin_y (the front-left corner -- Phase A/B's original, less intuitive behavior). CUSTOM uses pivot_x/pivot_y, set by dragging the pivot marker on canvas. See venues.generation._rotation_pivot_local, mirrored in static/js/seat_geometry.js's pivotLocal.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="pivot_x",
            field=models.FloatField(
                default=0.0,
                help_text="CUSTOM pivot_mode only: local x (same pre-rotation local frame as the seat grid, relative to origin_x) of the rotation pivot. Ignored otherwise.",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="pivot_y",
            field=models.FloatField(
                default=0.0,
                help_text="CUSTOM pivot_mode only: local y (same pre-rotation local frame as the seat grid, relative to origin_y) of the rotation pivot. Ignored otherwise.",
            ),
        ),
    ]
