# Generated by Django 5.2.16 on 2026-07-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0005_section_rotation_pivot"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="row_label_start",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Index into the row-label sequence where this section's FIRST row starts -- 0 (default) labels it A. Real houses often continue one letter sequence across tiers (Orchestra A-M, then a Parterre whose first row is N, a Balcony starting at V): set 12 / 19 (skip_io indices for N / V) on those sections so labels -- and therefore printed tickets -- match the house's own chart. Purely a labeling offset: never affects geometry. See venues.generation.generate_row_labels, mirrored in static/js/seat_geometry.js.",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="numbering_scheme",
            field=models.CharField(
                choices=[
                    ("sequential", "Sequential (1, 2, 3…)"),
                    ("odd_desc_left", "Odd, descending toward the aisle (…5, 3, 1)"),
                    (
                        "even_asc_right",
                        "Even, ascending away from the aisle (2, 4, 6…)",
                    ),
                    ("hundreds", "Hundreds by row (101, 102… / 201, 202…)"),
                    (
                        "hundreds_flat",
                        "Hundreds, same every row (101, 102… / 101, 102…)",
                    ),
                ],
                default="sequential",
                max_length=20,
            ),
        ),
    ]
