# Generated by Django 5.2.16 on 2026-07-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0006_section_row_label_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="seat_number_base",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Added to every generated seat number, composing with numbering_scheme -- many houses number their center blocks in the 100s while keeping the side blocks' odd/even convention: odd_desc_left with base 100 gives ...119, 117 ... 103, 101; even_asc_right with base 100 gives 102, 104... A pure label offset, like row_label_start: never affects geometry. See venues.generation.generate_seat_numbers, mirrored in static/js/seat_geometry.js.",
            ),
        ),
    ]
