# Generated by Django 5.2.16 on 2026-07-15 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_contactinquiry"),
        ("venues", "0007_section_seat_number_base"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartParseJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload", models.FileField(upload_to="chart_parse_uploads/%Y/%m/")),
                ("media_type", models.CharField(max_length=50)),
                (
                    "chart_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name override for a newly created chart.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "progress",
                    models.CharField(
                        blank=True,
                        help_text="Worker stage while running: extracting / verifying / building.",
                        max_length=50,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chart",
                    models.ForeignKey(
                        blank=True,
                        help_text="The resulting chart once the job succeeds.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="venues.seatingchart",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
                (
                    "replace_chart",
                    models.ForeignKey(
                        blank=True,
                        help_text="Re-parse INTO this chart (replace its sections). Null = create a new chart.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parse_jobs",
                        to="venues.seatingchart",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_parse_jobs",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization"], name="venues_char_organiz_81f6fe_idx"
                    ),
                    models.Index(
                        fields=["venue", "-created_at"],
                        name="venues_char_venue_i_e5f9fe_idx",
                    ),
                ],
            },
        ),
    ]
