# Generated by Django 5.2.16 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0007_section_seat_number_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="numbering_scheme",
            field=models.CharField(
                choices=[
                    ("sequential", "Sequential (1, 2, 3…)"),
                    ("odd_desc_left", "Odd, right to left (…5, 3, 1)"),
                    ("even_asc_right", "Even, left to right (2, 4, 6…)"),
                    ("hundreds", "Hundreds by row (101, 102… / 201, 202…)"),
                    (
                        "hundreds_flat",
                        "Hundreds, same every row (101, 102… / 101, 102…)",
                    ),
                ],
                default="sequential",
                max_length=20,
            ),
        ),
    ]
