# Generated by Django 5.2.16 on 2026-07-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0008_alter_section_numbering_scheme"),
        ("venues", "0008_chartparsejob"),
    ]

    operations = []
