# Generated by Django 5.2.16 on 2026-07-09 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("tenants", "0001_initial"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="performance",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performances",
                to="venues.venue",
            ),
        ),
        migrations.AddField(
            model_name="gaallocation",
            name="performance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ga_allocation",
                to="events.performance",
            ),
        ),
        migrations.AddField(
            model_name="pricetier",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="pricetier",
            name="performance",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for a GA performance's flat price tier.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_tiers",
                to="events.performance",
            ),
        ),
        migrations.AddField(
            model_name="pricetier",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for a reserved-seating price tier scoped to a Section.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_tiers",
                to="venues.section",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organization"], name="events_even_organiz_6d342c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organization", "status"], name="events_even_organiz_a2ef24_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_event_slug_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["organization"], name="events_perf_organiz_bff4a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["organization", "event"], name="events_perf_organiz_8f3ff9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["organization", "starts_at"],
                name="events_perf_organiz_fb91e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gaallocation",
            index=models.Index(
                fields=["organization"], name="events_gaal_organiz_553e60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gaallocation",
            index=models.Index(
                fields=["organization", "performance"],
                name="events_gaal_organiz_8af551_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gaallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("sold__lte", models.F("capacity"))),
                name="ga_sold_lte_capacity",
            ),
        ),
        migrations.AddIndex(
            model_name="pricetier",
            index=models.Index(
                fields=["organization"], name="events_pric_organiz_4dfe10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricetier",
            index=models.Index(
                fields=["organization", "performance"],
                name="events_pric_organiz_ac22f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricetier",
            index=models.Index(
                fields=["organization", "section"],
                name="events_pric_organiz_12f83d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricetier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("performance__isnull", False), ("section__isnull", True)),
                    models.Q(("performance__isnull", True), ("section__isnull", False)),
                    _connector="OR",
                ),
                name="price_tier_xor_performance_section",
            ),
        ),
    ]
