# Generated by Django 5.2.16 on 2026-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        ("tenants", "0001_initial"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pricetier",
            name="price_tier_xor_performance_section",
        ),
        migrations.AddConstraint(
            model_name="pricetier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("performance__isnull", False),
                    ("section__isnull", False),
                    _connector="OR",
                ),
                name="price_tier_requires_performance_or_section",
            ),
        ),
    ]
