# Generated by Django 5.2.16 on 2026-07-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_pricetier_allow_section_override"),
        ("tenants", "0001_initial"),
        ("venues", "0002_section_arc_radius_section_numbering_scheme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performance",
            name="seating_chart",
            field=models.ForeignKey(
                blank=True,
                help_text="Explicit chart choice for a RESERVED performance. Leave blank to use the venue's first seating chart (correct for the common one-chart-per-venue case).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performances",
                to="venues.seatingchart",
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["seating_chart"], name="events_perf_seating_b32f2d_idx"
            ),
        ),
    ]
