# Generated by Django 5.2.16 on 2026-07-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_backfill_performance_seating_chart"),
        ("tenants", "0001_initial"),
        ("venues", "0003_section_row_x_offset_alter_section_arc_radius"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_zones",
                        to="events.performance",
                    ),
                ),
            ],
            options={
                "ordering": ["performance", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingZoneSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_seats",
                        to="venues.seat",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_seats",
                        to="events.pricingzone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pricingzone",
            name="seats",
            field=models.ManyToManyField(
                blank=True,
                related_name="pricing_zones",
                through="events.PricingZoneSeat",
                to="venues.seat",
            ),
        ),
        migrations.CreateModel(
            name="ZoneTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "color",
                    models.CharField(
                        default="#2563eb",
                        help_text="Hex color, e.g. #2563eb.",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pricingzone",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="The template this zone was applied/cloned from, if any -- provenance only.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zones",
                to="events.zonetemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingzoneseat",
            index=models.Index(
                fields=["organization"], name="events_pric_organiz_a97e0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingzoneseat",
            index=models.Index(fields=["zone"], name="events_pric_zone_id_7e2235_idx"),
        ),
        migrations.AddIndex(
            model_name="pricingzoneseat",
            index=models.Index(fields=["seat"], name="events_pric_seat_id_ce08d7_idx"),
        ),
        migrations.AddConstraint(
            model_name="pricingzoneseat",
            constraint=models.UniqueConstraint(
                fields=("zone", "seat"), name="unique_seat_per_zone"
            ),
        ),
        migrations.AddIndex(
            model_name="zonetemplate",
            index=models.Index(
                fields=["organization"], name="events_zone_organiz_618cd4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="zonetemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_zone_template_name_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingzone",
            index=models.Index(
                fields=["organization"], name="events_pric_organiz_c958f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingzone",
            index=models.Index(
                fields=["organization", "performance"],
                name="events_pric_organiz_62075f_idx",
            ),
        ),
    ]
