# Generated by Django 5.0.14 on 2026-07-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "subdomain",
                    models.SlugField(
                        help_text="The subdomain this tenant is served on, e.g. 'roxy' for roxy.lab980.com.",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="org_logos/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#111111",
                        help_text="Hex color, e.g. #111111.",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#e11d48",
                        help_text="Hex color, e.g. #e11d48.",
                        max_length=7,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=63)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "stripe_publishable_key",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_secret_key", models.CharField(blank=True, max_length=255)),
                ("stripe_webhook_secret", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
