# Generated by Django 5.2.16 on 2026-07-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_organization_subdomain_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="infra_message",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="infra_status",
            field=models.CharField(
                choices=[
                    ("none", "Not provisioned"),
                    ("pending", "Queued"),
                    ("provisioning", "Provisioning…"),
                    ("provisioned", "Live"),
                    ("failed", "Failed"),
                ],
                db_default="none",
                default="none",
                max_length=20,
            ),
        ),
    ]
