# Generated by Django 5.2.16 on 2026-07-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_organization_infra_message_organization_infra_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="stripe_publishable_key",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="stripe_secret_key",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="stripe_webhook_secret",
        ),
        migrations.AddField(
            model_name="organization",
            name="platform_fee_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override platform fee % for this theater. Blank = use the global default.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_charges_enabled",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_details_submitted",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
