# Generated by Django 5.2.16 on 2026-07-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_organization_stripe_connect"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        help_text="The venue/theater the sender is asking about (optional).",
                        max_length=200,
                    ),
                ),
                ("message", models.TextField(max_length=5000)),
                ("is_handled", models.BooleanField(db_default=False, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "contact inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
