# Generated by Django 5.2.16 on 2026-07-15 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_contactinquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="dark_accent_color",
            field=models.CharField(
                default="#0e0e12",
                help_text="Deep shade for dark sections. Hex, e.g. #0e0e12.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                        "Enter a hex color like #4B2E83 or #abc.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="light_neutral_color",
            field=models.CharField(
                default="#f5f5f4",
                help_text="Light neutral background. Hex, e.g. #f5f5f4.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                        "Enter a hex color like #4B2E83 or #abc.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="neutral_color",
            field=models.CharField(
                default="#111111",
                help_text="Near-black neutral (body text). Hex, e.g. #111111.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                        "Enter a hex color like #4B2E83 or #abc.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="secondary_color",
            field=models.CharField(
                default="#374151",
                help_text="Secondary brand color. Hex, e.g. #374151.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                        "Enter a hex color like #4B2E83 or #abc.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="accent_color",
            field=models.CharField(
                default="#e11d48",
                help_text="Metallic / accent highlight (buttons, links). Hex, e.g. #e11d48.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                        "Enter a hex color like #4B2E83 or #abc.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="primary_color",
            field=models.CharField(
                default="#111111",
                help_text="Primary brand color. Hex, e.g. #111111.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                        "Enter a hex color like #4B2E83 or #abc.",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="ColorScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Enter a hex color like #4B2E83 or #abc.",
                            )
                        ],
                    ),
                ),
                (
                    "secondary",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Enter a hex color like #4B2E83 or #abc.",
                            )
                        ],
                    ),
                ),
                (
                    "dark_accent",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Enter a hex color like #4B2E83 or #abc.",
                            )
                        ],
                    ),
                ),
                (
                    "feature_accent",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Enter a hex color like #4B2E83 or #abc.",
                            )
                        ],
                    ),
                ),
                (
                    "light_neutral",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Enter a hex color like #4B2E83 or #abc.",
                            )
                        ],
                    ),
                ),
                (
                    "neutral",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                                "Enter a hex color like #4B2E83 or #abc.",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140)),
                ("is_preset", models.BooleanField(db_default=False, default=False)),
                ("source_url", models.URLField(blank=True, default="")),
                ("ordering", models.PositiveIntegerField(db_default=0, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_schemes",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "name"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="tenants_col_organiz_b4ceff_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("organization__isnull", True)),
                        fields=("slug",),
                        name="unique_preset_scheme_slug",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("organization__isnull", False)),
                        fields=("organization", "slug"),
                        name="unique_custom_scheme_slug_per_org",
                    ),
                ],
            },
        ),
    ]
