# Generated by Django 5.2.16 on 2026-07-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_seed_builtin_color_schemes"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="body_font",
            field=models.CharField(default="system-sans", max_length=40),
        ),
        migrations.AddField(
            model_name="organization",
            name="heading_font",
            field=models.CharField(default="system-sans", max_length=40),
        ),
    ]
