# Generated by Django 5.2.16 on 2026-07-15 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_rename_metallic_to_feature_accent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="accent_color",
            field=models.CharField(
                default="#e11d48",
                help_text="Feature Accent highlight (buttons, links). Hex, e.g. #e11d48.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                        "Enter a hex color like #4B2E83 or #abc.",
                    )
                ],
            ),
        ),
    ]
