# Generated by Django 5.2.16 on 2026-07-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_resync_harmonized_accents"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="page_tint",
            field=models.CharField(
                choices=[
                    ("none", "None — clean white"),
                    ("subtle", "Subtle — a hint of brand color"),
                    ("medium", "Medium — clearly branded"),
                    ("bold", "Bold — saturated ground"),
                ],
                default="subtle",
                help_text="How much brand color the storefront page background carries.",
                max_length=7,
            ),
        ),
    ]
