# Generated by Django 5.2.16 on 2026-07-16 20:24

import tenants.logo_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_rename_incongruous_schemes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Shown in your storefront header, emails, browser tab, and social-share cards. Large images are automatically resized.",
                null=True,
                upload_to="org_logos/",
                validators=[tenants.logo_images.validate_logo_upload],
            ),
        ),
    ]
