# Generated by Django 5.2.16 on 2026-07-12 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_organization_infra_message_organization_infra_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One-line teaser shown under the title in the article list.",
                        max_length=280,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text. Blank lines start a new paragraph; links are auto-detected."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("venue_rules", "Venue rules"),
                            ("show_info", "Show information"),
                            ("policies", "Policies"),
                            ("how_to", "Using Boxo"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public — ticket buyers & everyone"),
                            ("staff", "All staff"),
                            ("box_office", "Box office & up"),
                            ("manager", "Managers & owners"),
                            ("owner", "Owners only"),
                        ],
                        default="staff",
                        help_text="Who can read this. 'Public' also shows it on the storefront FAQ.",
                        max_length=20,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished drafts are only visible on the Manage screen.",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers sort first within a category.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "position", "title"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization"], name="helpcenter__organiz_acc25c_idx"
                    ),
                    models.Index(
                        fields=["organization", "visibility"],
                        name="helpcenter__organiz_7633de_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "slug"), name="unique_help_slug_per_org"
                    )
                ],
            },
        ),
    ]
