# Generated by Django 5.2.16 on 2026-07-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0004_organization_stripe_connect"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="General Fund", max_length=255)),
                ("acknowledgment", models.TextField(blank=True, default="")),
                (
                    "suggested_amounts",
                    models.CharField(default="10,25,50,100", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization"], name="donations_d_organiz_78abbd_idx"
                    ),
                    models.Index(
                        fields=["organization", "is_active"],
                        name="donations_d_organiz_f39781_idx",
                    ),
                ],
            },
        ),
    ]
