# Generated by Django 5.2.16 on 2026-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestaccount",
            name="marketing_opt_in",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="guestaccount",
            name="marketing_opt_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guestaccount",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="guestaccount",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
