"""Help center tests: model slug/visibility helpers, role-gated staff
reading, manager-only authoring (with tenant isolation), and the public
storefront FAQ (PUBLIC-only, tenant-host-only)."""

from django.test import TestCase

from accounts.models import Membership
from accounts.tests import StaffFixtureMixin, host_for
from venues.tests import make_org

from . import builtins
from .models import HelpArticle

Vis = HelpArticle.Visibility
Cat = HelpArticle.Category


def make_article(org, title="Note", visibility=Vis.STAFF, **kwargs):
    kwargs.setdefault("body", "Some body text.")
    return HelpArticle.objects.create(
        organization=org, title=title, visibility=visibility, **kwargs
    )


class HelpArticleModelTests(TestCase):
    def setUp(self):
        self.org = make_org("roxy")

    def test_slug_autogenerated_from_title(self):
        a = make_article(self.org, title="House Rules & Info")
        self.assertEqual(a.slug, "house-rules-info")

    def test_slug_unique_per_org(self):
        make_article(self.org, title="Policies")
        b = make_article(self.org, title="Policies")
        self.assertEqual(b.slug, "policies-2")

    def test_same_slug_allowed_across_orgs(self):
        other = make_org("palace")
        a = make_article(self.org, title="Policies")
        b = make_article(other, title="Policies")
        self.assertEqual(a.slug, b.slug)  # scoped per org, no clash

    def test_explicit_slug_preserved(self):
        a = make_article(self.org, title="Whatever", slug="custom")
        self.assertEqual(a.slug, "custom")


class VisibilityGatingTests(StaffFixtureMixin, TestCase):
    def setUp(self):
        self.org = make_org("roxy")
        self.public = make_article(self.org, title="Buyer info", visibility=Vis.PUBLIC)
        self.staff = make_article(self.org, title="Door notes", visibility=Vis.STAFF)
        self.box = make_article(self.org, title="Refund steps", visibility=Vis.BOX_OFFICE)
        self.mgr = make_article(self.org, title="Ops runbook", visibility=Vis.MANAGER)
        self.owner_only = make_article(self.org, title="Billing", visibility=Vis.OWNER)
        self.draft = make_article(
            self.org, title="WIP", visibility=Vis.STAFF, is_published=False
        )

    def _readable(self, role):
        membership = Membership(organization=self.org, role=role)
        return set(
            HelpArticle.objects.readable_by(self.org, membership).values_list(
                "title", flat=True
            )
        )

    def test_scanner_sees_public_and_staff_only(self):
        self.assertEqual(self._readable(Membership.Role.SCANNER), {"Buyer info", "Door notes"})

    def test_box_office_adds_box_office(self):
        self.assertEqual(
            self._readable(Membership.Role.BOX_OFFICE),
            {"Buyer info", "Door notes", "Refund steps"},
        )

    def test_manager_adds_manager(self):
        self.assertEqual(
            self._readable(Membership.Role.MANAGER),
            {"Buyer info", "Door notes", "Refund steps", "Ops runbook"},
        )

    def test_owner_sees_everything_published(self):
        self.assertEqual(
            self._readable(Membership.Role.OWNER),
            {"Buyer info", "Door notes", "Refund steps", "Ops runbook", "Billing"},
        )

    def test_drafts_never_in_readable(self):
        self.assertNotIn("WIP", self._readable(Membership.Role.OWNER))

    def test_public_manager_returns_public_published_only(self):
        titles = set(HelpArticle.objects.public(self.org).values_list("title", flat=True))
        self.assertEqual(titles, {"Buyer info"})


class BuiltinTests(TestCase):
    def test_public_builtins_are_all_public(self):
        self.assertTrue(builtins.public())
        self.assertTrue(all(a.visibility == Vis.PUBLIC for a in builtins.public()))

    def test_scanner_builtins_exclude_manager_content(self):
        scanner = Membership(role=Membership.Role.SCANNER)
        vis = {a.visibility for a in builtins.readable_by(scanner)}
        self.assertNotIn(Vis.MANAGER, vis)
        self.assertNotIn(Vis.BOX_OFFICE, vis)

    def test_owner_sees_more_builtins_than_scanner(self):
        owner = Membership(role=Membership.Role.OWNER)
        scanner = Membership(role=Membership.Role.SCANNER)
        self.assertGreater(len(builtins.readable_by(owner)), len(builtins.readable_by(scanner)))

    def test_builtin_display_helpers(self):
        a = builtins.public()[0]
        # Must not raise and must resolve to the model's labels.
        self.assertTrue(a.get_visibility_display())
        self.assertTrue(a.get_category_display())
        self.assertTrue(a.is_builtin)

    # -- Phase 5: patron-revenue help content -------------------------------

    def _slugs(self, membership_role):
        membership = Membership(role=membership_role)
        return {a.slug for a in builtins.readable_by(membership)}

    def test_new_revenue_builtins_present_and_unique(self):
        slugs = [a.slug for a in builtins.BUILTIN_ARTICLES]
        self.assertEqual(len(slugs), len(set(slugs)))
        for slug in (
            "discounts-and-promo-codes",
            "season-and-flex-passes",
            "donations",
            "email-marketing-and-your-audience",
            "getting-your-box-office-set-up",
        ):
            self.assertIn(slug, slugs)

    def test_manager_sees_all_new_revenue_guides(self):
        slugs = self._slugs(Membership.Role.MANAGER)
        self.assertIn("discounts-and-promo-codes", slugs)
        self.assertIn("season-and-flex-passes", slugs)
        self.assertIn("donations", slugs)
        self.assertIn("email-marketing-and-your-audience", slugs)
        self.assertIn("getting-your-box-office-set-up", slugs)

    def test_box_office_does_not_see_manager_only_revenue_guides(self):
        # All five revenue guides describe manager-gated authoring workflows
        # (promo/pass/donation/campaign CRUD, box-office setup), so none are
        # box_office-visible -- a box-office reader would be pointed at pages
        # their role can't open.
        slugs = self._slugs(Membership.Role.BOX_OFFICE)
        self.assertNotIn("discounts-and-promo-codes", slugs)
        self.assertNotIn("season-and-flex-passes", slugs)
        self.assertNotIn("donations", slugs)
        self.assertNotIn("email-marketing-and-your-audience", slugs)
        self.assertNotIn("getting-your-box-office-set-up", slugs)

    def test_scanner_does_not_see_new_revenue_guides(self):
        slugs = self._slugs(Membership.Role.SCANNER)
        for slug in (
            "discounts-and-promo-codes",
            "season-and-flex-passes",
            "donations",
            "email-marketing-and-your-audience",
            "getting-your-box-office-set-up",
        ):
            self.assertNotIn(slug, slugs)

    def test_new_revenue_builtins_are_not_public(self):
        public_slugs = {a.slug for a in builtins.public()}
        for slug in (
            "discounts-and-promo-codes",
            "season-and-flex-passes",
            "donations",
            "email-marketing-and-your-audience",
            "getting-your-box-office-set-up",
        ):
            self.assertNotIn(slug, public_slugs)


class StaffHelpViewTests(StaffFixtureMixin, TestCase):
    def setUp(self):
        self.org = make_org("roxy")
        self.host = host_for("roxy")
        make_article(self.org, title="Door notes", visibility=Vis.STAFF)
        make_article(self.org, title="Ops runbook", visibility=Vis.MANAGER)

    def test_help_index_requires_login(self):
        resp = self.client.get("/dashboard/help/", HTTP_HOST=self.host)
        self.assertEqual(resp.status_code, 302)  # -> login

    def test_scanner_sees_help_but_not_manager_article(self):
        user, _ = self.make_staff(self.org, Membership.Role.SCANNER)
        self.client.force_login(user)
        resp = self.client.get("/dashboard/help/", HTTP_HOST=self.host)
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Door notes")
        self.assertNotContains(resp, "Ops runbook")
        # Built-in fallback shows too.
        self.assertContains(resp, "Working the door")

    def test_manager_sees_manager_article_and_manage_link(self):
        user, _ = self.make_staff(self.org, Membership.Role.MANAGER)
        self.client.force_login(user)
        resp = self.client.get("/dashboard/help/", HTTP_HOST=self.host)
        self.assertContains(resp, "Ops runbook")
        self.assertContains(resp, "Manage articles")

    def test_manager_sees_new_patron_revenue_guides_rendered(self):
        user, _ = self.make_staff(self.org, Membership.Role.MANAGER)
        self.client.force_login(user)
        resp = self.client.get("/dashboard/help/", HTTP_HOST=self.host)
        self.assertContains(resp, "Discounts &amp; promo codes")
        self.assertContains(resp, "Season &amp; flex passes")
        self.assertContains(resp, "Donations")
        self.assertContains(resp, "Email marketing &amp; your audience")
        self.assertContains(resp, "Getting your box office set up")

    def test_box_office_does_not_see_manager_only_revenue_guides_rendered(self):
        # The revenue guides all describe manager-gated authoring flows, so a
        # box-office login sees none of them (it would otherwise be pointed at
        # pages its role can't open).
        user, _ = self.make_staff(self.org, Membership.Role.BOX_OFFICE)
        self.client.force_login(user)
        resp = self.client.get("/dashboard/help/", HTTP_HOST=self.host)
        self.assertNotContains(resp, "Discounts &amp; promo codes")
        self.assertNotContains(resp, "Season &amp; flex passes")
        self.assertNotContains(resp, "Donations")
        self.assertNotContains(resp, "Email marketing &amp; your audience")

    def test_scanner_cannot_open_manage(self):
        user, _ = self.make_staff(self.org, Membership.Role.SCANNER)
        self.client.force_login(user)
        resp = self.client.get("/dashboard/help/manage/", HTTP_HOST=self.host)
        self.assertEqual(resp.status_code, 403)

    def test_manager_can_create_article(self):
        user, _ = self.make_staff(self.org, Membership.Role.MANAGER)
        self.client.force_login(user)
        resp = self.client.post(
            "/dashboard/help/new/",
            {
                "title": "Late seating policy",
                "slug": "",
                "summary": "",
                "category": Cat.POLICIES,
                "visibility": Vis.PUBLIC,
                "body": "Latecomers seated at a suitable break.",
                "position": 0,
                "is_published": "on",
            },
            HTTP_HOST=self.host,
        )
        self.assertRedirects(resp, "/dashboard/help/manage/", fetch_redirect_response=False)
        article = HelpArticle.objects.get(title="Late seating policy")
        self.assertEqual(article.organization, self.org)
        self.assertEqual(article.created_by, user)
        self.assertEqual(article.slug, "late-seating-policy")

    def test_manager_cannot_edit_other_orgs_article(self):
        other = make_org("palace")
        foreign = make_article(other, title="Not yours")
        user, _ = self.make_staff(self.org, Membership.Role.MANAGER)
        self.client.force_login(user)
        resp = self.client.get(
            f"/dashboard/help/{foreign.pk}/edit/", HTTP_HOST=self.host
        )
        self.assertEqual(resp.status_code, 404)

    def test_manager_can_delete(self):
        article = make_article(self.org, title="Temporary")
        user, _ = self.make_staff(self.org, Membership.Role.MANAGER)
        self.client.force_login(user)
        resp = self.client.post(
            f"/dashboard/help/{article.pk}/delete/", HTTP_HOST=self.host
        )
        self.assertRedirects(resp, "/dashboard/help/manage/", fetch_redirect_response=False)
        self.assertFalse(HelpArticle.objects.filter(pk=article.pk).exists())


class PublicFaqViewTests(TestCase):
    def setUp(self):
        self.org = make_org("roxy")
        self.host = host_for("roxy")
        make_article(self.org, title="Buyer info", visibility=Vis.PUBLIC)
        make_article(self.org, title="Staff only door notes", visibility=Vis.STAFF)
        make_article(
            self.org, title="Public draft", visibility=Vis.PUBLIC, is_published=False
        )

    def test_faq_shows_public_published_only(self):
        resp = self.client.get("/faq/", HTTP_HOST=self.host)
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Buyer info")
        self.assertNotContains(resp, "Staff only door notes")
        self.assertNotContains(resp, "Public draft")

    def test_faq_includes_public_builtins_and_contact(self):
        resp = self.client.get("/faq/", HTTP_HOST=self.host)
        self.assertContains(resp, "Ticket buyer FAQ")  # a public builtin
        self.assertContains(resp, self.org.contact_email)

    def test_faq_404_on_platform_host(self):
        resp = self.client.get("/faq/")  # bare host, no tenant
        self.assertEqual(resp.status_code, 404)
