# Generated by Django 5.2.16 on 2026-07-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0006_pricingzone_pricingzoneseat_pricingzone_seats_and_more"),
        ("guests", "0001_initial"),
        ("orders", "0011_hold_donation_amount_hold_donation_campaign_and_more"),
        ("tenants", "0004_organization_stripe_connect"),
        ("venues", "0005_section_rotation_pivot"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("season", "Season"), ("flex", "Flex")], max_length=16
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credit_count", models.PositiveIntegerField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True, related_name="pass_products", to="events.event"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PassPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("season", "Season"), ("flex", "Flex")], max_length=16
                    ),
                ),
                ("credit_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "credits_remaining",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("exhausted", "Exhausted"),
                            ("refunded", "Refunded"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "covered_events",
                    models.ManyToManyField(
                        blank=True, related_name="covering_passes", to="events.event"
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passes",
                        to="guests.guestaccount",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pass_purchases",
                        to="orders.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="passes.passproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PassRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credits_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pass_redemptions",
                        to="events.event",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pass_redemptions",
                        to="orders.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
                (
                    "pass_purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="passes.passpurchase",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pass_redemptions",
                        to="events.performance",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pass_redemptions",
                        to="venues.seat",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pass_redemption",
                        to="orders.ticket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="passproduct",
            index=models.Index(
                fields=["organization"], name="passes_pass_organiz_223a1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passproduct",
            index=models.Index(
                fields=["organization", "is_active"],
                name="passes_pass_organiz_7c0efc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="passproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)),
                name="passproduct_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="passproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("credit_count__gt", 0),
                        ("credit_count__isnull", False),
                        ("kind", "flex"),
                    ),
                    models.Q(("credit_count__isnull", True), ("kind", "season")),
                    _connector="OR",
                ),
                name="passproduct_credit_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="passpurchase",
            index=models.Index(
                fields=["organization"], name="passes_pass_organiz_24a1ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passpurchase",
            index=models.Index(
                fields=["organization", "guest"], name="passes_pass_organiz_6f7532_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passpurchase",
            index=models.Index(
                fields=["organization", "status"], name="passes_pass_organiz_481bcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passredemption",
            index=models.Index(
                fields=["organization"], name="passes_pass_organiz_77ce44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passredemption",
            index=models.Index(
                fields=["organization", "pass_purchase"],
                name="passes_pass_organiz_897119_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="passredemption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("credits_used", 0)),
                fields=("pass_purchase", "event"),
                name="unique_season_event_redemption",
            ),
        ),
    ]
