# Generated by Django 5.2.16 on 2026-07-09 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("orders", "0001_initial"),
        ("tenants", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="holdseat",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hold_seats",
                to="venues.seat",
            ),
        ),
        migrations.AddField(
            model_name="hold",
            name="seats",
            field=models.ManyToManyField(
                blank=True,
                related_name="holds",
                through="orders.HoldSeat",
                to="venues.seat",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="events.performance",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="events.pricetier",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="venues.seat",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="events.performance",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="scanned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scanned_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="venues.seat",
            ),
        ),
        migrations.AddIndex(
            model_name="holdseat",
            index=models.Index(
                fields=["organization"], name="orders_hold_organiz_1c1232_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holdseat",
            index=models.Index(fields=["hold"], name="orders_hold_hold_id_8c7fbf_idx"),
        ),
        migrations.AddIndex(
            model_name="holdseat",
            index=models.Index(fields=["seat"], name="orders_hold_seat_id_3a99db_idx"),
        ),
        migrations.AddConstraint(
            model_name="holdseat",
            constraint=models.UniqueConstraint(
                fields=("hold", "seat"), name="unique_seat_per_hold"
            ),
        ),
        migrations.AddIndex(
            model_name="hold",
            index=models.Index(
                fields=["organization"], name="orders_hold_organiz_96dd9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hold",
            index=models.Index(
                fields=["organization", "performance"],
                name="orders_hold_organiz_6e55be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hold",
            index=models.Index(
                fields=["performance", "expires_at"],
                name="orders_hold_perform_c70fc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hold",
            index=models.Index(
                fields=["session_key"], name="orders_hold_session_229ea5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("price_tier__isnull", True), ("quantity__isnull", True)),
                    models.Q(
                        ("price_tier__isnull", False), ("quantity__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="hold_ga_fields_together",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["organization"], name="orders_orde_organiz_97975a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["organization", "performance"],
                name="orders_orde_organiz_4dbe1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["organization", "status"], name="orders_orde_organiz_b4ac87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["stripe_checkout_session_id"],
                name="orders_orde_stripe__338ca2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["organization"], name="orders_orde_organiz_a1d1a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="orders_orde_order_i_5d347b_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization"], name="orders_paym_organiz_1adbc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["order"], name="orders_paym_order_i_8c8d98_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization"], name="orders_tick_organiz_1f003e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "performance"],
                name="orders_tick_organiz_2ff09c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["performance", "seat"], name="orders_tick_perform_e5e724_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("seat__isnull", False), models.Q(("status", "void"), _negated=True)
                ),
                fields=("performance", "seat"),
                name="unique_live_ticket_per_performance_seat",
            ),
        ),
    ]
