# Generated by Django 5.2.16 on 2026-07-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_pricetier_allow_section_override"),
        ("orders", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("stripe_checkout_session_id__isnull", True), _negated=True
                    ),
                    models.Q(("stripe_checkout_session_id", ""), _negated=True),
                ),
                fields=("organization", "stripe_checkout_session_id"),
                name="unique_stripe_checkout_session_per_org",
            ),
        ),
    ]
