# Generated by Django 5.2.16 on 2026-07-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_performance_seating_chart_and_more"),
        ("orders", "0003_order_unique_stripe_checkout_session_per_org"),
        ("tenants", "0001_initial"),
        ("venues", "0002_section_arc_radius_section_numbering_scheme_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceSeatBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.organization",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_blocks",
                        to="events.performance",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_blocks",
                        to="venues.seat",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization"], name="orders_perf_organiz_d11d3d_idx"
                    ),
                    models.Index(
                        fields=["organization", "performance"],
                        name="orders_perf_organiz_a2b61d_idx",
                    ),
                    models.Index(
                        fields=["performance", "seat"],
                        name="orders_perf_perform_2ca5ff_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("performance", "seat"),
                        name="unique_seat_block_per_performance",
                    )
                ],
            },
        ),
    ]
