# Generated by Django 5.2.16 on 2026-07-09 19:22

import django.db.models.deletion
from django.db import migrations, models


def backfill_unit_amount_from_price_tier(apps, schema_editor):
    """Phase C (seating-chart epic): unit_amount is new -- every pre-existing
    HoldSeat row was necessarily priced via price_tier (zones didn't exist
    yet), so backfill its snapshot from there. Any Hold this touches is
    short-lived (10-minute expiry -- see orders.models.default_hold_expiry)
    so this only matters for a hold that happens to be mid-flight while this
    migration runs; it's still correct to backfill rather than leave it at
    the AddField's one-off 0.00 default."""
    HoldSeat = apps.get_model("orders", "HoldSeat")
    for hold_seat in HoldSeat.objects.filter(price_tier__isnull=False).select_related("price_tier"):
        hold_seat.unit_amount = hold_seat.price_tier.amount
        hold_seat.save(update_fields=["unit_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_pricingzone_pricingzoneseat_pricingzone_seats_and_more"),
        ("orders", "0004_performanceseatblock"),
        ("tenants", "0001_initial"),
        ("venues", "0003_section_row_x_offset_alter_section_arc_radius"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdseat",
            name="pricing_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hold_seats",
                to="events.pricingzone",
            ),
        ),
        migrations.AddField(
            model_name="holdseat",
            name="unit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Snapshot of the resolved price at hold-creation time -- see class docstring.",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_unit_amount_from_price_tier, migrations.RunPython.noop),
        migrations.AddField(
            model_name="orderitem",
            name="pricing_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="events.pricingzone",
            ),
        ),
        migrations.AlterField(
            model_name="holdseat",
            name="price_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hold_seats",
                to="events.pricetier",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="events.pricetier",
            ),
        ),
        # Deliberately NO "at least one of price_tier/pricing_zone" check
        # constraint here -- see HoldSeat's and OrderItem's docstrings
        # (orders/models.py): deleting a PricingZone is allowed even with
        # live holds/orders referencing it (events.zones.delete_zone),
        # which SET_NULLs pricing_zone on rows whose price_tier is already
        # null (because they were zone-priced in the first place). Such a
        # constraint would make that delete raise IntegrityError, which
        # contradicts "seats already sold/held can still be zoned... a zone
        # can be deleted" from docs/SEATING.md. unit_amount is the field
        # that's always populated and always authoritative -- see its
        # help_text above.
    ]
