# Generated by Django 5.2.16 on 2026-07-10 14:58

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_holdseat_pricing_zone_holdseat_unit_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="token",
            field=models.CharField(
                default=orders.models.new_token,
                editable=False,
                max_length=36,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="token",
            field=models.CharField(
                default=orders.models.new_token,
                editable=False,
                max_length=36,
                unique=True,
            ),
        ),
    ]
