# Generated by Django 5.2.16 on 2026-07-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_initial"),
        ("orders", "0006_alter_order_token_alter_ticket_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="guests.guestaccount",
            ),
        ),
    ]
