# Generated by Django 5.2.16 on 2026-07-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="hold",
            name="ga_unit_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
