# Generated by Django 5.2.16 on 2026-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_hold_ga_unit_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="hold",
            name="discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
