# Generated by Django 5.2.16 on 2026-07-14 14:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_hold_discount_amount"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hold",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holds",
                to="promotions.promocode",
            ),
        ),
        migrations.AddField(
            model_name="hold",
            name="promo_code_text",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code_text",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
