# Generated by Django 5.2.16 on 2026-07-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
        ("events", "0006_pricingzone_pricingzoneseat_pricingzone_seats_and_more"),
        ("orders", "0010_hold_promo_code_hold_promo_code_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hold",
            name="donation_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="hold",
            name="donation_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holds",
                to="donations.donationcampaign",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="donation_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="donations.donationcampaign",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ticket", "Ticket"),
                    ("donation", "Donation"),
                    ("pass", "Pass"),
                ],
                db_default="ticket",
                default="ticket",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="performance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="events.performance",
            ),
        ),
    ]
