# Generated by Django 5.2.16 on 2026-07-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_hold_donation_amount_hold_donation_campaign_and_more"),
        ("passes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="pass_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="passes.passproduct",
            ),
        ),
    ]
